---
abstract: 'Locale::MO::File - Write or read gettext MO files.'
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
build_requires:
  Data::Hexdumper: 0
  Hash::Util: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-MO-File
provides:
  Locale::MO::File:
    file: lib/Locale/MO/File.pm
    version: 0.01
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  Carp: 0
  Encode: 0
  English: 0
  IO::File: 0
  Moose: 0
  MooseX::FollowPBP: 0
  MooseX::StrictConstructor: 0
  Params::Validate: 0
  Readonly: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
